### ISSUE TITLE
System.Exception: Types of ApiModule cannot be instantiated before RichHudClient is initialized

### ISSUE THREAD

**Issue by doctorspooky** [ZachHembree/BuildVision2#4]
Excerpt from my log:

2024-08-10 13:22:56.387 - Thread:   1 ->  [Build Vision] Mod encountered an unhandled exception.
System.TypeInitializationException: The type initializer for 'DarkHelmet.BuildVision2.BindsConfig' threw an exception. 
   ---> System.Exception: Types of ApiModule cannot be instantiated before RichHudClient is initialized.
   at RichHudFramework.UI.Client.BindManager..ctor()
   at RichHudFramework.UI.Client.BindManager.Init()
   at RichHudFramework.UI.ControlData..ctor(MyKeys key)
   at RichHudFramework.UI.ControlData.op_Implicit(MyKeys key)
   at DarkHelmet.BuildVision2.BindsConfig..cctor()
   --- End of inner exception stack trace ---
   at DarkHelmet.BuildVision2.BindsConfig.GetDefaults()
   at DarkHelmet.BuildVision2.BvConfig.GetDefaults()
   at RichHudFramework.IO.ConfigRoot`1.ConfigIO.ValidateConfig(ConfigT cfg)
   at RichHudFramework.IO.ConfigRoot`1.ConfigIO.Load(Boolean silent)
   at RichHudFramework.IO.ConfigRoot`1.Load(Boolean silent)
   at RichHudFramework.IO.ConfigRoot`1.get_Current()
   at RichHudFramework.IO.ConfigRoot`1.Save()
   at DarkHelmet.BuildVision2.BvMain.BeforeClose()
   at RichHudFramework.Internal.ExceptionHandler.<>c__DisplayClass77_1.<CloseClients>b__0()
   at RichHudFramework.Internal.ExceptionHandler.Run(Action Action)

I'll delete the folder inside the %appdata directory, and see if it fixes it, and let you know!

**Comment by doctorspooky** [comment]
Update:  Nope!  This is being played single player, and this mod is being loaded after RichHUD.

**Comment by Gredys** [comment]
For some reason still an issue. Seems like some conbination of mods, tried to toggle off/on some to determine what is happening and switching order - but no luck.

Using `R.I.S.E Modpack` ( https://steamcommunity.com/sharedfiles/filedetails/?id=3443822406 ) mod list (with same order from their Guide) on `Khurakan System` ( https://steamcommunity.com/sharedfiles/filedetails/?id=2852224218 ) world.
The only changes I made:
 - Moved planets after `API's & Frameworks` category in the modpack guide 
 - Removed `pulley` mod

Moving `Rich HUD Master` on top or somewhere else - doesn't fix the issue. Still game same error as @doctorspooky 

P.S. Was using it few days ago on another save it it was fine, no any errors. But now I can't load save with BuildVision enabled O..o
